#!/usr/bin/env python3
"""Write CATALOG-MAP.md: every scene the phone can choose from, by world and kind.

    ./catalog-map.py

A world is the time and culture a book lives in; a kind is what the reader sees. Both are defined
in taxonomy.json, which also tags the scenes bundled with the app, since those are not in the
manifest. The map is what to read before planning new scenes: a hole in the grid is a kind of
place a world's books visit and the catalog cannot show.

It fails, and writes nothing, if any scene is untagged or uses a world or kind the taxonomy does
not define. merge-staged.py runs it after every merge.
"""

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPOSITORY = HERE.parent / "app/src/main/java/com/immersialabs/infinitereading/data/environment/EnvironmentRepository.kt"


def bundled_names():
    """The scenes seeded into the app, read the way tools/embedder-bench/catalog_coverage.py reads them."""
    src = REPOSITORY.read_text()
    default = re.search(r'DEFAULT_FLAT_ENVIRONMENT_NAME\s*=\s*"([^"]+)"', src).group(1)
    return [m.group(2) or default
            for m in re.finditer(r'name\s*=\s*("([^"]+)"|DEFAULT_FLAT_ENVIRONMENT_NAME)\s*,\s*description', src)]


def load():
    taxonomy = json.loads((HERE / "taxonomy.json").read_text())
    scenes = [dict(s, source="published") for s in json.loads((HERE / "manifest.json").read_text())["scenes"]]
    for path in sorted((HERE / "staged").glob("wave-*.json")):
        scenes += [dict(s, source="staged") for s in json.loads(path.read_text())]
    problems = []
    names = bundled_names()
    for name in names:
        tags = taxonomy["bundled"].get(name)
        if tags is None:
            problems.append(f"bundled scene '{name}' has no tags in taxonomy.json")
        else:
            scenes.append({"name": name, "world": tags["world"], "kind": tags["kind"], "source": "bundled"})
    for name in taxonomy["bundled"]:
        if name not in names:
            problems.append(f"taxonomy.json tags '{name}', which is not bundled with the app")
    for s in scenes:
        label = s.get("id", s["name"])
        if s.get("world") not in taxonomy["worlds"]:
            problems.append(f"{label}: world {s.get('world')!r} is not in taxonomy.json")
        if s.get("kind") not in taxonomy["kinds"]:
            problems.append(f"{label}: kind {s.get('kind')!r} is not in taxonomy.json")
    if problems:
        sys.exit("CATALOG-MAP.md not written:\n  " + "\n  ".join(problems))
    return taxonomy, scenes


def render(taxonomy, scenes):
    worlds, kinds = taxonomy["worlds"], taxonomy["kinds"]
    count = {src: sum(s["source"] == src for s in scenes) for src in ("published", "bundled", "staged")}

    def cell(world, kind):
        live = sum(s["world"] == world and s["kind"] == kind and s["source"] != "staged" for s in scenes)
        staged = sum(s["world"] == world and s["kind"] == kind and s["source"] == "staged" for s in scenes)
        text = str(live) if live else "·"
        return text + (f" +{staged}" if staged else "")

    lines = [
        "# Catalog map",
        "",
        "Generated by `catalog-map.py` from `manifest.json`, `taxonomy.json`, the scenes bundled with "
        "the app and anything waiting in `staged/`. Rebuild it rather than editing it.",
        "",
        f"**{count['published'] + count['bundled']} scenes** the phone can choose from: "
        f"{count['published']} published in the catalog and {count['bundled']} bundled with the app"
        + (f", plus {count['staged']} staged and waiting for art." if count["staged"] else "."),
        "",
        "## Worlds by kind",
        "",
        "Each number is how many scenes of that kind a world has, and `·` is a hole: somewhere that "
        "world's books go and the catalog cannot show. Staged scenes show as `+n`.",
        "",
        "| | " + " | ".join(k["name"] for k in kinds.values()) + " | all |",
        "|---|" + "---|" * (len(kinds) + 1),
    ]
    for wid, world in worlds.items():
        total = sum(s["world"] == wid and s["source"] != "staged" for s in scenes)
        lines.append(f"| **{world['name']}** | " + " | ".join(cell(wid, kid) for kid in kinds) + f" | {total} |")
    lines.append("| **all** | " + " | ".join(
        str(sum(s["kind"] == kid and s["source"] != "staged" for s in scenes)) for kid in kinds)
        + f" | {count['published'] + count['bundled']} |")
    lines += ["", "## Scenes by world", ""]
    lines.append("Bundled scenes are marked *(bundled)*, and staged scenes *(staged)*.")
    for wid, world in worlds.items():
        members = [s for s in scenes if s["world"] == wid]
        lines += ["", f"### {world['name']} — {sum(s['source'] != 'staged' for s in members)}", "", world["summary"], ""]
        for kid, kind in kinds.items():
            here = sorted((s for s in members if s["kind"] == kid), key=lambda s: s["name"])
            if here:
                names = ", ".join(s["name"] + (f" *({s['source']})*" if s["source"] != "published" else "") for s in here)
                lines.append(f"- **{kind['name']}:** {names}")
    lines += ["", "## The kinds", ""]
    lines += [f"- **{k['name']}** (`{kid}`): {k['summary']}" for kid, k in kinds.items()]
    lines += ["", "## The worlds", ""]
    lines += [f"- **{w['name']}** (`{wid}`): {w['summary']}" for wid, w in worlds.items()]
    return "\n".join(lines) + "\n"


def main():
    taxonomy, scenes = load()
    (HERE / "CATALOG-MAP.md").write_text(render(taxonomy, scenes))
    print(f"CATALOG-MAP.md: {len(scenes)} scenes")


if __name__ == "__main__":
    main()
